name: package_signature
description: a easy way to get android package signature on flutter app.
version: 1.1.1+1
homepage: https://github.com/laiiihz/package_signature

environment:
  sdk: ^3.10.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  convert: ^3.1.1
dev_dependencies:
  pigeon: ^24.2.1

flutter:
  plugin:
    platforms:
      android:
        package: tech.laihz.package_signature
        pluginClass: PackageSignaturePlugin
